* Saliendo de la crisis
La abeja reina dijo hace unos cuantos meses que la colmena estaba por
fin saliendo de la crisis. Ahora Maya quiere comprobar cómo de ciertas
eran aquellas declaraciones, ası́ que ha recopilado el histórico de
distintos indicadores económicos desde el dı́a de la declaración hasta
hoy para ver si, efectivamente, todos ellos han ido creciendo dı́a a
dı́a desde entonces.

** Entrada

La entrada estará compuesta de distintos indicadores económicos, cada
uno de ellos en dos lı́neas distintas. La primera lı́nea indica el
número de muestras recogidas del indicador (0 < n ≤ 100). La segunda
lı́nea contiene n números positivos con los valores económicos (entre 1
y 10.000.000) medidos desde el dı́a de la declaración de la abeja reina
hasta el dı́a de hoy.  La entrada termina con un indicador sin muestras
(0) que no debe procesarse.

** Salida

Por cada caso de prueba se dirá si según ese indicador la abeja reina
tenı́a razón (SI) o las cosas no están tan bien como ella cree (NO).

** Entrada de ejemplo

3
1 3 6
4
1 3 2 5
3
6 6 6
0

** Salida de ejemplo

SI
NO
NO
